# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: bot-app CI/CD

on:
     push:
          branches: ["main"]

jobs:
     build:
          runs-on: self-hosted
          strategy:
               matrix:
                    node-version: [18.x]
                    # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
          env:
               working-directory: ./bot
               APP_PORT: ${{ secrets.APP_PORT }}
               TK: ${{ secrets.TK }}
          steps:
               - uses: actions/checkout@v3
               - name: Use Node.js ${{ matrix.node-version }}
                 uses: actions/setup-node@v3
                 with:
                      node-version: ${{ matrix.node-version }}
                      cache: "npm"
                      cache-dependency-path: "bot/package-lock.json"
               - run: npm i
                 working-directory: ${{env.working-directory}}
               - run: npm ci
                 working-directory: ${{env.working-directory}}
               - run: npm test
                 working-directory: ${{env.working-directory}}
                 continue-on-error: true
                 name: Run App
               - run: pm2 restart Botapp
                 working-directory: ${{env.working-directory}}
